#ApplicationURL
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#browser_configuration
browser=chrome

#credentials
username=Admin
password=admin123

#implicitWait(In Seconds)
ImplicitWait=10

//ExplicitWait
ExplicitWait=30